name: 'PR Tasks Completed Check'
on: 
  pull_request:
    types: [opened, edited]

jobs:
  task-check:
    permissions:
      checks: write
      issues: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: chromaui/task-completed-checker-action@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"